version: '3.9'

services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads   
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    
volumes:
  deluge-downloads: {}
  deluge-config: {}
