version: '3.5'
services:
  parsedmarc:
    image: patschi/parsedmarc
    volumes:
      - dmarc-input:/input
      - dmarc-output:/output
    command: parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - discovery.type=single-node

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'

  sftp:
    image: drakkan/sftpgo
    volumes:
        - dmarc-imput:/srv/sftpgo
        - sftpgo-config:/var/lib/sftpgo  
    ports:
        - 2022:2022
        - 8080:8080

volumes:
  dmarc-input: {}
  dmarc-output: {}
  sftpgo-config: {}
