version: '3.9'

services:
  php-httpd:
    image: php:7.3-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - http-data:/var/www/html

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBRootPassword}
      MYSQL_DATABASE: LAMP-DB
      MYSQL_USER: DBClient
      MYSQL_PASSWORD: ${DBClientPassword}

  php-myadmin:
    links:
      - db
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      

volumes:
  db-data: {}
  http-data: {}
