version: "3.9"

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - syncthing-appdata:/config
      - syncthing-data1:/data1
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

volumes:
  syncthing-appdata: {}
  syncthing-data1: {}
